# Spring auto Config will connect for local config (if external means change the values)
spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}

# Custom RabbitMQ Queue Properties
rabbit:
  mq:
    queue:
      exchange-name: vedha-exchange
      normal: # Supports String
        name: vedha-queue
        routing-key-name: vedha-routing
      json: # Supports Json
        name: vedha-json-queue
        routing-key-name: vedha-json-routing

management:
  info:
    java:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  health:
    rabbit:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Spring Boot RabbitMQ Demo
    environment: ${spring.profiles.active}
    version: '@project.version@' # Reading From Pom