# Spring auto Config will connect for local config (if external means change the values)
spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}

# Custom RabbitMQ Queue Properties
rabbit:
  mq:
    queue:
      exchange-name: vedha-exchange
      normal: # Supports String
        name: vedha-queue
        routing-key-name: vedha-routing
      json: # Supports Json
        name: vedha-json-queue
        routing-key-name: vedha-json-routing